### ISSUE TITLE
Autoformat code cells in notebooks with nbQA

### ISSUE THREAD

**Issue by redeboer** [ComPWA/K-matrix-research#18]
As a follow-up to #16, to decrease the diffs per commit and to make the code more standardised and readable, we can add an additional hook to the `.pre-commit-config.yaml` that applies [black](https://black.readthedocs.io) formatting to code cells and sorts import with [isort](https://pycqa.github.io/isort). The additional hook looks like this (more info [here](https://github.com/nbQA-dev/nbQA#pre-commit)):

```yaml
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.0
    hooks:
      - id: nbqa-black
      - id: nbqa-isort
```
